export const GET_OPERATIONS = "GET_OPERATIONS";
export const GET_OPERATIONS_BY_OFFER_ID = "GET_OPERATIONS_BY_OFFER_ID";
export const SET_OPERATIONS_GRID_LOADING = "SET_OPERATIONS_GRID_LOADING";
export const ADD_OPERATION = "ADD_OPERATION";