export const ADD_OFFER = "ADD_OFFER";
export const UPDATE_OFFER = "UPDATE_OFFER";
export const GET_OFFERS = "GET_OFFERS";
export const SET_OFFER_OVERLAY_LOADING = "SET_OFFER_OVERLAY_LOADING";
export const SET_OFFERS_GRID_LOADING = "SET_OFFERS_GRID_LOADING";
export const OFFER_DETAIL_PAGE_LOADING = "OFFER_DETAIL_PAGE_LOADING";