export const GET_PARTS = "GET_PARTS";
export const GET_PARTS_BY_OFFER_ID = "GET_PARTS_BY_OFFER_ID";
export const ADD_PART = "ADD_PART";
export const UPDATE_PART = "UPDATE_PART";
export const DELETE_PART = "DELETE_PART";
export const SET_PARTS_GRID_LOADING = "SET_PARTS_GRID_LOADING";
export const SET_PART_OVERLAY_LOADING = "SET_PART_OVERLAY_LOADING";
export const CONVERT_PART_MODEL_FILE = "CONVERT_PART_MODEL_FILE";